# Generated by Django 4.2.2 on 2023-06-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerId', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=15)),
                ('merchantId', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('top1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top1', to='core.store')),
                ('top2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top2', to='core.store')),
                ('top3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top3', to='core.store')),
                ('top4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top4', to='core.store')),
                ('top5', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top5', to='core.store')),
            ],
            options={
                'db_table': 'Item',
            },
        ),
    ]
