# Generated by Django 4.2.2 on 2023-06-29 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
        migrations.AlterField(
            model_name='item',
            name='top1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top1', to='core.store'),
        ),
        migrations.AlterField(
            model_name='item',
            name='top2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top2', to='core.store'),
        ),
        migrations.AlterField(
            model_name='item',
            name='top3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top3', to='core.store'),
        ),
        migrations.AlterField(
            model_name='item',
            name='top4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top4', to='core.store'),
        ),
        migrations.AlterField(
            model_name='item',
            name='top5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top5', to='core.store'),
        ),
    ]
