# Generated by Django 4.2.2 on 2023-06-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_top1_alter_item_top2_alter_item_top3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='top1Price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='top2Price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='top3Price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='top4Price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='top5Price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
